import { AVAILABLE_MODELS, DEFAULT_MODEL_ID } from "@/lib/models"

export type IntentType = "coding" | "creative" | "analysis" | "image" | "research" | "reasoning" | "enterprise" | "general"

export interface RoutingResult {
  intent: IntentType
  intentLabel: string
  confidence: number
  modelId: string
}

const INTENT_PHRASES: Record<IntentType, string[]> = {
  coding: [
    "build a function",
    "write code",
    "debug",
    "fix a bug",
    "refactor",
    "implement",
    "stack trace",
    "api",
    "set up a backend",
    "add an endpoint",
    "write a script",
    "compose a query",
    "optimize this function",
    "type error",
    "compiler error",
    "lint error",
    "unit test",
    "integration test",
    "create a class",
    "design an interface",
    "make a component",
    "build a feature",
    "ship a patch",
    "bug reproduction",
    "runtime error",
    "segmentation fault",
    "null pointer",
    "stack overflow",
    "memory leak",
    "data structure",
    "algorithm design",
    "big o analysis",
    "sql query",
    "database schema",
    "migrate a database",
    "write a migration",
    "api client",
    "webhook handler",
    "typescript error",
    "python traceback",
    "node error",
    "dockerfile",
    "kubernetes manifest",
    "ci pipeline",
    "github actions",
    "deployment script",
    "refactor component",
    "code review",
    "pair programming",
    "implement feature flag",
    "optimize query",
    "performance profiling",
  ],
  creative: [
    "write a story",
    "craft a narrative",
    "creative writing",
    "poem",
    "lyrics",
    "script",
    "brand voice",
    "brand voice pipeline",
    "marketing copy",
    "ad copy",
    "tagline ideas",
    "slogan ideas",
    "product description",
    "rewrite for tone",
    "rewrite in a friendly tone",
    "rewrite in a professional tone",
    "rewrite in a business voice",
    "storytelling",
    "short story",
    "character sketch",
    "world building",
    "dialogue writing",
    "screenplay",
    "pitch deck narrative",
    "creative brief",
    "campaign concept",
    "social media post",
    "press release draft",
    "email campaign",
    "brand narrative",
    "voice and tone",
    "style guide",
    "copywriting",
    "headline ideas",
    "subject line ideas",
    "landing page copy",
    "about us copy",
    "product launch copy",
    "creative concept",
  ],
  analysis: [
    "analyze",
    "analysis",
    "compare",
    "forecast",
    "summarize",
    "data insights",
    "critical analytical problem",
    "root cause analysis",
    "performance analysis",
    "tradeoff analysis",
    "risk analysis",
    "cost benefit analysis",
    "profitability analysis",
    "financial analysis",
    "strategic analysis",
    "market analysis",
    "competitive analysis",
    "business analysis",
    "funnel analysis",
    "cohort analysis",
    "revenue analysis",
    "pricing analysis",
    "growth analysis",
    "customer analysis",
    "unit economics",
    "kpi analysis",
    "metric review",
    "statistical analysis",
    "variance analysis",
    "scenario analysis",
    "sensitivity analysis",
    "decision analysis",
    "diagnostic analysis",
    "data modeling",
    "data exploration",
    "data audit",
    "analyze a dataset",
    "interpret results",
    "explain the numbers",
    "investigate anomaly",
    "trend analysis",
    "time series analysis",
    "forecast demand",
    "model performance",
    "evaluate model",
    "benchmark results",
  ],
  reasoning: [
    "reasoning",
    "logical reasoning",
    "complex reasoning",
    "multi-step reasoning",
    "deductive reasoning",
    "inductive reasoning",
    "abductive reasoning",
    "formal reasoning",
    "critical thinking",
    "analytical problem",
    "critical analytical problem",
    "logic puzzle",
    "prove",
    "derive",
    "step by step solution",
    "math proof",
    "optimization problem",
    "constraint solving",
    "graph theory",
    "combinatorics",
    "number theory",
    "dynamic programming",
    "leetcode",
    "leercode",
    "coding interview",
    "technical interview",
    "problem solving",
    "puzzle",
    "brain teaser",
    "algorithmic reasoning",
    "explain your reasoning",
    "show your reasoning",
  ],
  image: [
    "generate an image",
    "create an image",
    "illustration",
    "visual design",
    "poster",
    "logo",
    "diagram",
    "infographic",
    "wireframe",
    "mockup",
    "render",
    "artwork",
    "icon set",
    "brand mark",
    "character art",
    "storyboard",
    "product render",
    "photo realistic",
    "concept art",
    "visual concept",
    "design a logo",
    "design a poster",
    "image generation",
  ],
  research: [
    "research",
    "literature review",
    "academic",
    "citations",
    "study",
    "research summary",
    "survey the literature",
    "systematic review",
    "evidence review",
    "market research",
    "competitive landscape",
    "benchmark study",
    "whitepaper",
    "case study",
    "industry report",
    "regulatory review",
    "compliance research",
    "policy analysis",
    "business strategy",
    "go to market",
    "product strategy",
    "customer discovery",
    "user research",
    "stakeholder analysis",
    "explore sources",
    "compile sources",
    "academic sources",
    "citation needed",
    "reference list",
  ],
  enterprise: [
    "business workflow",
    "business process",
    "enterprise workflow",
    "enterprise process",
    "operating model",
    "operating cadence",
    "standard operating procedure",
    "sop",
    "business pipeline",
    "sales pipeline",
    "crm workflow",
    "customer success workflow",
    "finance workflow",
    "procurement workflow",
    "compliance workflow",
    "risk management workflow",
    "governance workflow",
    "organizational design",
    "org chart",
    "stakeholder management",
    "enterprise architecture",
    "business transformation",
    "change management",
    "process improvement",
    "lean process",
    "six sigma",
    "business operations",
    "operations strategy",
    "business strategy",
    "enterprise planning",
    "program management",
    "portfolio management",
    "okrs",
    "kpis for business",
    "resource planning",
    "budget planning",
    "vendor management",
    "service management",
    "itil",
    "policy design",
    "risk controls",
  ],
  general: [],
}

const INTENT_SEMANTIC_TOKENS: Record<IntentType, string[]> = {
  coding: [
    "code",
    "function",
    "class",
    "compile",
    "bug",
    "error",
    "script",
    "algorithm",
    "refactor",
    "debug",
    "endpoint",
    "api",
    "query",
    "database",
    "schema",
    "migration",
    "typescript",
    "javascript",
    "python",
    "java",
    "golang",
    "rust",
    "test",
    "ci",
    "pipeline",
    "deployment",
    "docker",
    "kubernetes",
    "frontend",
    "backend",
    "ui",
    "component",
    "library",
    "framework",
    "performance",
  ],
  creative: [
    "story",
    "narrative",
    "creative",
    "imagine",
    "write",
    "tone",
    "voice",
    "poem",
    "lyrics",
    "script",
    "brand",
    "copy",
    "copywriting",
    "slogan",
    "tagline",
    "headline",
    "campaign",
    "pitch",
    "storytelling",
    "character",
    "dialogue",
    "style",
    "rewrite",
  ],
  analysis: [
    "analyze",
    "analysis",
    "insight",
    "compare",
    "evaluate",
    "metrics",
    "data",
    "statistics",
    "trend",
    "forecast",
    "anomaly",
    "diagnostic",
    "root",
    "cause",
    "risk",
    "tradeoff",
    "optimization",
    "kpi",
    "revenue",
    "pricing",
    "profit",
    "margin",
    "strategy",
    "market",
    "business",
    "unit",
    "economics",
    "variance",
    "scenario",
    "sensitivity",
    "model",
    "benchmark",
    "performance",
  ],
  reasoning: [
    "reasoning",
    "logical",
    "logic",
    "deduction",
    "induction",
    "abduction",
    "proof",
    "derive",
    "optimize",
    "constraints",
    "puzzle",
    "brain",
    "teaser",
    "problem",
    "solve",
    "leetcode",
    "leercode",
    "interview",
    "algorithm",
    "combinatorics",
    "graph",
    "dp",
    "math",
  ],
  image: [
    "image",
    "visual",
    "render",
    "illustration",
    "design",
    "photo",
    "art",
    "diagram",
    "infographic",
    "wireframe",
    "mockup",
    "logo",
    "poster",
    "icon",
    "concept",
    "storyboard",
  ],
  research: [
    "research",
    "study",
    "paper",
    "citations",
    "sources",
    "academic",
    "survey",
    "literature",
    "evidence",
    "systematic",
    "review",
    "whitepaper",
    "report",
    "benchmark",
    "industry",
    "market",
    "competitive",
    "regulatory",
    "policy",
    "compliance",
    "strategy",
    "go-to-market",
  ],
  enterprise: [
    "enterprise",
    "business",
    "workflow",
    "process",
    "operations",
    "strategy",
    "governance",
    "compliance",
    "sop",
    "pipeline",
    "crm",
    "sales",
    "finance",
    "procurement",
    "risk",
    "controls",
    "org",
    "portfolio",
    "program",
    "budget",
    "vendor",
    "service",
    "itil",
  ],
  general: [],
}

const INTENT_LABELS: Record<IntentType, string> = {
  coding: "Coding",
  creative: "Creative",
  analysis: "Analysis",
  reasoning: "Reasoning",
  image: "Image",
  research: "Research",
  enterprise: "Enterprise",
  general: "General",
}

const MODEL_PRIORITY: Record<IntentType, string[]> = {
  coding: ["Qwen/Qwen3-Coder-480B-A35B-Instruct", "Qwen/Qwen2.5-Coder-7B-Instruct"],
  creative: ["Qwen/Qwen3-Next-80B-A3B-Instruct", "moonshotai/Kimi-K2-Instruct"],
  analysis: ["deepseek-ai/DeepSeek-V3.2-Exp", "google/gemini-2.5-pro"],
  reasoning: ["deepseek-ai/DeepSeek-V3.2-Exp", "google/gemini-2.5-pro"],
  image: ["stabilityai/stable-diffusion-xl-base-1.0"],
  research: ["google/gemini-2.5-pro", "deepseek-ai/DeepSeek-V3.2-Exp"],
  enterprise: ["meta-llama/Llama-3.3-70B-Instruct", "zai-org/GLM-4.5-Air"],
  general: [DEFAULT_MODEL_ID],
}

function findAvailableModel(modelIds: string[]): string | null {
  for (const id of modelIds) {
    if (AVAILABLE_MODELS.some((model) => model.id === id)) {
      return id
    }
  }
  return null
}

export function getRoutingRecommendation(prompt: string): RoutingResult {
  const normalized = prompt.toLowerCase()
  const tokens = new Set(
    normalized
      .replace(/[^a-z0-9\s]/g, " ")
      .split(/\s+/)
      .filter(Boolean)
  )

  const scores = (Object.keys(INTENT_PHRASES) as IntentType[]).map((intent) => {
    const phraseMatches = INTENT_PHRASES[intent].filter((phrase) => normalized.includes(phrase)).length
    const tokenMatches = INTENT_SEMANTIC_TOKENS[intent].filter((token) => tokens.has(token)).length
    const score = phraseMatches * 3 + tokenMatches
    return { intent, score }
  })

  const best = scores.sort((a, b) => b.score - a.score)[0]
  const resolvedIntent = best.score > 0 ? best.intent : "general"
  const modelId = findAvailableModel(MODEL_PRIORITY[resolvedIntent]) ?? DEFAULT_MODEL_ID
  const confidence = Math.min(95, 45 + best.score * 8)

  return {
    intent: resolvedIntent,
    intentLabel: INTENT_LABELS[resolvedIntent],
    confidence,
    modelId,
  }
}
